"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import locale
import os

os.environ['PYTHONIOENCODING'] = 'utf-8'
locale.setlocale(locale.LC_ALL, 'es_AR.UTF-8') # Fuerza el locale de Argentina

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carpeta física en tu computadora donde Django guardará las fotos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0td6kbnqn382d)tl9^4w9(vv2#%am+m(l_0vt&%*@35pj1=w#w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# CONFIGURACIÓN DE ENVÍO DE EMAILS (GMAIL)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nachozubri15@gmail.com' # Tu correo de Gmail
EMAIL_HOST_PASSWORD = 'iwfkddsbrnccqycn'  # PEGA ACÁ TU CONTRASEÑA DE 16 CARACTERES
DEFAULT_FROM_EMAIL = 'Telas APP <nachozubri15@gmail.com>'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tus aplicaciones
    'products',      # <--- ¡ESTA LÍNEA ES LA QUE FALTA!
    'rest_framework',
    'corsheaders',

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'appecomercce', 
        'USER': 'postgres',
        'PASSWORD': 'Matias2003',
        'HOST': 'localhost',
        'PORT': '3000',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        }
    }
}
 

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Le damos permiso a tu frontend de Vite
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ============================================================
# CONFIGURACIÓN DE OPTIMIZACIÓN DE IMÁGENES CON PILLOW
# ============================================================
# Ubicación de archivos de media (donde Django guarda imágenes subidas)
MEDIA_URL = '/media/'

# Formatos de imagen permitidos
ALLOWED_IMAGE_FORMATS = ['JPEG', 'JPG', 'PNG', 'GIF', 'WEBP']

# Parámetros de optimización para diferentes tipos de imágenes
IMAGE_OPTIMIZATION_SETTINGS = {
    'THUMBNAILS': {
        'max_width': 500,
        'max_height': 500,
        'quality': 85,
    },
    'PRODUCT_IMAGES': {
        'max_width': 1000,
        'max_height': 1000,
        'quality': 85,
    },
    'GALLERY_IMAGES': {
        'max_width': 800,
        'max_height': 800,
        'quality': 85,
    },
    'BANNERS': {
        'max_width': 2000,
        'max_height': 1200,
        'quality': 85,
    }
}

# Pillow - Optimización automática de imágenes
PILLOW_SETTINGS = {
    'JPEG_QUALITY': 85,
    'PNG_COMPRESS_LEVEL': 9,
    'WEBP_QUALITY': 85,
}
