"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import locale
import os
# ✅ AGREGÁ ESTAS DOS LÍNEAS:
from dotenv import load_dotenv
load_dotenv()  # Lee el .env automáticamente

os.environ['PYTHONIOENCODING'] = 'utf-8'
locale.setlocale(locale.LC_ALL, 'es_AR.UTF-8') # Fuerza el locale de Argentina

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carpeta física en tu computadora donde Django guardará las fotos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0td6kbnqn382d)tl9^4w9(vv2#%am+m(l_0vt&%*@35pj1=w#w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# CONFIGURACIÓN DE ENVÍO DE EMAILS (GMAIL)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend' # ahora aqui va resend, en production deberías usar un correo verificado de resend
EMAIL_HOST_PASSWORD = os.environ.get('RESEND_API_KEY', '')  # La API key va en tu .env local, nunca acá
# DEFAULT_FROM_EMAIL = 'Telas APP <nachozubri15@gmail.com>'
# Como aún no verificaste un dominio propio, DEBES usar este remitente de prueba:
DEFAULT_FROM_EMAIL = "Telas APP <ventas@modaytelas.com.ar>"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tus aplicaciones
    'products',      # <--- ¡ESTA LÍNEA ES LA QUE FALTA!
    'rest_framework',
    'corsheaders',

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# Si la variable 'PYTHONANYWHERE_DOMAIN' existe, significa que el código está en producción
if 'PYTHONANYWHERE_DOMAIN' in os.environ:
    # ☁️ CONFIGURACIÓN DE PYTHONANYWHERE (MySQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'ignaciozurbrigge$Telas-App',
            'USER': 'ignaciozurbrigge',
            'PASSWORD': 'nacho2003',
            'HOST': 'ignaciozurbriggen.mysql.pythonanywhere-services.com',
            'PORT': '3306',
        }
    }
else:
    # 💻 CONFIGURACIÓN LOCAL (PostgreSQL en tu VS Code)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'Telas-App', 
            'USER': 'postgres',
            'PASSWORD': 'Nacho2003',
            'HOST': 'localhost',
            'PORT': '3000',
            'OPTIONS': {
                'client_encoding': 'UTF8',
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Le damos permiso a tu frontend de Vite
    "https://modaytelas.com.ar",
    "https://www.modaytelas.com.ar",
]

# Autenticación del panel de admin vía JWT (login con usuario/contraseña).
# El permiso por defecto sigue siendo AllowAny para no romper la tienda pública;
# las vistas del admin declaran permission_classes=[IsAdminUser] explícitamente.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    # Vida larga a propósito: varias vistas del admin usan fetch() nativo,
    # que no refresca el token solo (solo axios lo hace acá).
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ============================================================
# CONFIGURACIÓN DE OPTIMIZACIÓN DE IMÁGENES CON PILLOW
# ============================================================
# Ubicación de archivos de media (donde Django guarda imágenes subidas)
MEDIA_URL = '/media/'

# Formatos de imagen permitidos
ALLOWED_IMAGE_FORMATS = ['JPEG', 'JPG', 'PNG', 'GIF', 'WEBP']

# Parámetros de optimización para diferentes tipos de imágenes
IMAGE_OPTIMIZATION_SETTINGS = {
    'THUMBNAILS': {
        'max_width': 500,
        'max_height': 500,
        'quality': 85,
    },
    'PRODUCT_IMAGES': {
        'max_width': 1000,
        'max_height': 1000,
        'quality': 85,
    },
    'GALLERY_IMAGES': {
        'max_width': 800,
        'max_height': 800,
        'quality': 85,
    },
    'BANNERS': {
        'max_width': 2000,
        'max_height': 1200,
        'quality': 85,
    }
}

# Pillow - Optimización automática de imágenes
PILLOW_SETTINGS = {
    'JPEG_QUALITY': 85,
    'PNG_COMPRESS_LEVEL': 9,
    'WEBP_QUALITY': 85,
}


# CONFIGURACIÓN DE MERCADO PAGO
MP_APP_ID = os.environ.get('MP_APP_ID')
MP_CLIENT_SECRET = os.environ.get('MP_CLIENT_SECRET')