# Generated by Django 6.0.4 on 2026-05-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producto_imagen_productoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Tela / Producto', 'verbose_name_plural': 'Telas / Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talle',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si es una categoría principal. Seleccionar una si es subcategoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria', verbose_name='Categoría Padre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.PositiveIntegerField(default=150, help_text='Ejemplo: 150, 180, 300', verbose_name='Ancho (cm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_metro',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='Precio por Metro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_metros',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Cantidad de metros de largo disponibles en el rollo.', max_digits=10, verbose_name='Stock disponible (Metros)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria', verbose_name='Categoría / Subcategoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Tela'),
        ),
    ]
