# Generated by Django 6.0.4 on 2026-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producto_options_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_id', models.CharField(max_length=100, unique=True)),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
