# Generated by Django 6.0.4 on 2026-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
