# Generated by Django 6.0.4 on 2026-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_storeconfiguration_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='main_image',
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Principal 1'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Principal 2'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Principal 3'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/secundarias/', verbose_name='Imagen Secundaria 1'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='banners/secundarias/', verbose_name='Imagen Secundaria 2'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Instagram'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='logo_desarrollador',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Desarrollador'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Principal'),
        ),
    ]
