# Generated by Django 6.0.4 on 2026-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_storeconfiguration_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_padre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='productos', to='products.categoria', verbose_name='Categorías'),
        ),
    ]
