# Generated by Django 6.0.4 on 2026-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_categoria_categoria_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_favorito',
            field=models.BooleanField(default=False, verbose_name='Tela Favorita/Destacada'),
        ),
    ]
