# Generated by Django 6.0.4 on 2026-05-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_producto_es_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle_items',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default='Cliente', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Pago (MP)'), ('Esperando_Transferencia', 'Esperando Transferencia'), ('Aprobado', 'Pago Aprobado'), ('Cancelado', 'Cancelado / Expirado'), ('Despachado', 'Pedido Despachado')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mp_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID MercadoPago'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad_metros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto')),
            ],
        ),
    ]
