# Generated by Django 6.0.4 on 2026-05-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_pedido_detalle_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
