# Generated by Django 6.0.1 on 2026-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_pedido_detalle_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="direccion_envio",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Método/Dirección de Envío",
            ),
        ),
    ]
