# Generated by Django 6.0.4 on 2026-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_pedido_direccion_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=10, unique=True, verbose_name='Código Postal')),
                ('localidad', models.CharField(max_length=100, verbose_name='Nombre de la Localidad/Barrio')),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Envío ($)')),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitar esta ruta')),
            ],
            options={
                'verbose_name': 'Tarifa de Comisionista Local',
                'verbose_name_plural': 'Tarifas de Comisionistas Locales',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Envío Cobrado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Envío (Local/Envia.com)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='alto_estandar',
            field=models.PositiveIntegerField(default=10, verbose_name='Alto Estándar (cm)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='ancho_estandar',
            field=models.PositiveIntegerField(default=20, verbose_name='Ancho Estándar (cm)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='api_key_envia',
            field=models.CharField(blank=True, help_text='Pega aquí el Token generado en el panel de Envia.com', max_length=255, null=True, verbose_name='Token API Envia.com'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='largo_estandar',
            field=models.PositiveIntegerField(default=30, verbose_name='Largo Estándar (cm)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='peso_estandar',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Peso Estándar (kg)'),
        ),
    ]
