# Generated by Django 6.0.4 on 2026-05-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_tarifalocal_pedido_costo_envio_pedido_tipo_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='envia_carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='envia_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
