# Generated by Django 6.0.4 on 2026-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_pedido_envia_carrier_pedido_envia_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Envío (Local/Envia.com)'),
        ),
    ]
