# Generated by Django 6.0.4 on 2026-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_pedido_tipo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='url_etiqueta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
