# Generated by Django 6.0.4 on 2026-05-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_pedido_tracking_number_pedido_url_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Color')),
                ('codigo_hex', models.CharField(default='#FFFFFF', help_text='Ejemplo: #FF0000 para rojo', max_length=7, verbose_name='Código Hexadecimal')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.color', verbose_name='Color Principal'),
        ),
    ]
