# Generated by Django 6.0.4 on 2026-05-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_color_producto_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Uso (Ej: Eventos, Pantalones)')),
            ],
            options={
                'verbose_name': 'Uso de Tela',
                'verbose_name_plural': 'Usos de Telas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='usos',
            field=models.ManyToManyField(blank=True, related_name='telas', to='products.usotela', verbose_name='Telas para...'),
        ),
    ]
